Realestate_management_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
   path('',views.index,name="index"),
   path('home/',views.home,name="home"),
   path('view_property/<int:prop>/',views.view_prop,name="view_prop"),
   path('tenant/',views.tenant_view,name="tenant"),
   path('logout/',views.logout_user,name="logout"),
   path('add_property/',views.add_property,name="add_property"),
   path('add_unit/<int:id>/',views.add_unit,name="add_unit"),
   path('allocate_tenant/<int:unit>/<int:prop>/',views.allocate_tenant,name="allocate_tenant"),
]

core/models.py
from datetime import timedelta
from django.db import models

# Create your models here.

from django.db import models

class Property(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()
    location = models.CharField(max_length=255)
    features = models.TextField()
    image = models.ImageField(upload_to='property_images',null=True,default='no-property-photo.jpg')

    class Meta:
        verbose_name_plural = "Properties"

    def __str__(self):
        return self.name

    

class Unit(models.Model):
    name = models.CharField(max_length=100, default='flat',null=True,blank=True)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')])
    rent_cost = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    features = models.TextField()

    def __str__(self):
        return self.name

class Tenant(models.Model):
    unit = models.OneToOneField(Unit, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    monthly_rent_date = models.DateField()
    lease_expiry_date = models.DateField()
    document_proof = models.FileField(upload_to='document_proof/',null=True, blank=True)
    def __str__(self):
        return self.name
    

custom_user/models.py
from django_use_email_as_username.models import BaseUser, BaseUserManager


class User(BaseUser):
    objects = BaseUserManager()

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.

def index(request):
    if request.method == 'POST':
       
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)

        if user is not None:
            
            login(request, user)
            messages.success(request, 'Login successful.')
            return redirect('core:home') 
        else:
            messages.error(request, 'Invalid email or password.')
        return redirect('core:index')
    else:
        return render(request, 'index.html')
    
@login_required(login_url='core:index')
def home(request):
    if request.method == 'POST':
        key = request.POST['key']
        print(key)

        try:
            property = Property.objects.filter(Q(features__icontains=key) | Q(name__icontains=key))
        except:
            property=""
    else:
        property = Property.objects.all()
   
    
    context = {'property':property}

    return render(request,'home.html',context)

@login_required(login_url='core:index')
def view_prop(request,prop):
    property = Property.objects.filter(id=prop).first()

    try:
        unit = Unit.objects.filter(property=property)
    except:
        messages.info(request,'No units vailable in this property')
    tenant_det = []
    for un in unit:
        try:
            tenant = Tenant.objects.filter(unit = un) #[tenant1]
            new_unit={"unit":un,"tenant":tenant.first()}
            tenant_det.append(new_unit)
        except:
            pass

    context = {'tenant_det':tenant_det,'property':property}
    return render(request,'viewproperty.html',context)

@login_required(login_url='core:index')
def tenant_view(request):
    tenant = Tenant.objects.all()
    context = {'tenant':tenant}
    return render(request, 'tenant.html',context)

def logout_user(request):
    logout(request)

    return redirect('core:index')


@login_required(login_url='core:index')
def add_property(request):
    if request.method == 'POST':
        name = request.POST['name']
        address = request.POST['address']
        location = request.POST['location']
        features = request.POST['features']
        image = request.FILES['image']

        try:
            property = Property.objects.create(name=name,address=address,location=location,features=features,image=image)
            property.save()
            messages.success(request,'Property added successfully')
            return redirect('core:home')
        except:
            messages.error(request,"Couldn't add property")
            return redirect('core:home')
    else:
        return redirect('core:home')
    
@login_required(login_url='core:index')    
def add_unit(request, id):
    property = Property.objects.filter(id=id).first()

    if request.method == 'POST':
        name = request.POST['name']
        type = request.POST['type']
        rent = request.POST['rent']
        features = request.POST['features']

        try:
            unit = Unit.objects.create(name=name,type=type,rent_cost=rent,features=features,property=property)
            unit.save()
            messages.success(request, 'Unit added Successfully !')
            return redirect('core:view_prop', prop=property.id)
        except:
            messages.error(request, "Couldn't add Unit !")
            return redirect('core:view_prop', prop=property.id)
    else:
        return redirect('core:view_prop', prop=property.id)
    
@login_required(login_url='core:index')
def allocate_tenant(request, unit, prop):

    unit_data = Unit.objects.filter(id=unit).first()
    property_data = Property.objects.filter(id=prop).first()
    context={'unit':unit_data,'property':property_data}

    if request.method == 'POST':
        name=request.POST['name']
        address=request.POST['address']
        rentdate=request.POST['rentdate']
        expirydate=request.POST['expirydate']
        document=request.FILES['document']
        
        try:
            tenant = Tenant.objects.create(name=name,unit=unit_data,address=address,monthly_rent_date=rentdate,lease_expiry_date=expirydate,document_proof=document)
            tenant.save()
            unit_data.is_available=False
            unit_data.save()
            messages.success(request,'Tenant allocated Successfully !')
            return redirect('core:tenant')
        except:
            messages.error(request,"Couldn't allocate tenant !")
            return render(request,'addtenant.html',context)


    else:
        return render(request,'addtenant.html',context)
        

templates/addtenant.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Real Estate Management System</title>
    <style>
      body {
        background: url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D') center/cover no-repeat fixed;
      }

      .title {
        font-family: 'Comic Sans MS', cursive;
        font-size: 24px;
        color: #5c8a8a;
        margin-bottom: 20px;
        text-align:center;
      }
        .container {
            margin-top: 50px;
            max-width: 600px; /* Set the maximum width of the container */
            background-color: white; /* Set white background */
            padding: 20px;
            border-radius: 10px; /* Optional: Add rounded corners */
        }
  

    </style>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
        <div class="container-fluid">
          <a class="navbar-brand" href="/home/">Real Estate</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/home/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/home/">Our Properties</a>
              </li>
      
              <li class="nav-item">
                <a class="nav-link" href="/tenant/" tabindex="-1" aria-disabled="true">Our Tenants</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout/" tabindex="-1" aria-disabled="true">Logout</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
    
      {% if messages %}
      <div class="d-flex align-items-center justify-content-center mt-4">
        <div class="alert alert-warning alert-dismissible fade show w-50" role="alert">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {% endfor %}
        </div>
      </div>
        {% endif %}
        
          <div class="container">
            <h1 class="title">Allocate Tenant</h1>
            <form action="{% url 'core:allocate_tenant' unit=unit.id prop=property.id %}" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="propertyName" class="form-label">Tenant Name</label>
                    <input type="text" class="form-control" id="propertyName" name="name" required>
                </div>
                <div class="mb-3">
                    <label for="propertyAddress" class="form-label">Tenant Address</label>
                    <textarea class="form-control" id="propertyAddress" name="address" rows="3" required></textarea>
                </div>
                <div class="mb-3">
                    <label for="monthlyRentDate" class="form-label">Monthly Rent Date</label>
                    <input type="date" class="form-control" id="monthlyRentDate" name="rentdate" required>
                </div>
                <div class="mb-3">
                    <label for="leaseExpiryDate" class="form-label">Lease Expiry Date</label>
                    <input type="date" class="form-control" id="leaseExpiryDate" name="expirydate" required>
                </div>
                <div class="mb-3">
                    <label for="documentProof" class="form-label">Document Proof</label>
                    <input type="file" class="form-control" id="documentProof" name="document" accept=".pdf, .doc, .docx" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Real Estate Management System</title>
    <style>
      body {
        background: url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D') center/cover no-repeat fixed;
      }

      .title {
        font-family: 'Comic Sans MS', cursive;
        font-size: 24px;
        color: #5c8a8a;
        margin-bottom: 20px;
        text-align:center;
      }
  

    </style>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
        <div class="container-fluid">
          <a class="navbar-brand" href="/home/">Real Estate</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/home/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/home/">Our Properties</a>
              </li>
      
              <li class="nav-item">
                <a class="nav-link" href="/tenant/" tabindex="-1" aria-disabled="true">Our Tenants</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout/" tabindex="-1" aria-disabled="true">Logout</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
          <div class="title">
            <h1>Our Properties</h1>
          </div>

          <form action="/home/" method='POST'>
            {% csrf_token %}
              <div class="d-flex align-items-center justify-content-center">
            <input class="form-control mx-2 w-25" type="search" name="key" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary">Search</a>
            </div>
            </form>

          <div class="d-flex align-items-center justify-content-center mt-4">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPropertyModal">Add Property</button>
          </div>
          
          {% if messages %}
          <div class="d-flex align-items-center justify-content-center mt-4">
            <div class="alert alert-warning alert-dismissible fade show w-50" role="alert">
                {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {% endfor %}
            </div>
          </div>
            {% endif %}

      <div class="container mt-4">
        <div class="row">
          {% for prop in property %}
          <div class="col-md-4 mb-4">
            <div class="card">
              <img src="{{prop.image.url}}" class="card-img-top" alt="Property 1 Image" width="100%" height="200px" >
              <div class="card-body">
                <h5 class="card-title">{{prop.name}}</h5>
                <a href="{% url 'core:view_prop' prop=prop.id %}" class="btn btn-primary">View Details</a>
              </div>
            </div>
          </div>
          {% endfor %}
          
 
        </div>
      </div>

      
      <!-- Add Property Modal -->
<div class="modal fade" id="addPropertyModal" tabindex="-1" aria-labelledby="addPropertyModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addPropertyModalLabel">Add New Property</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <form id="addPropertyForm" action="{% url 'core:add_property' %}" method = 'POST' enctype='multipart/form-data'>
          {% csrf_token %}

          <div class="mb-3">
            <label for="propertyName" class="form-label">Property Name</label>
            <input type="text" required class="form-control" id="propertyName" name="name" required>
          </div>
          <div class="mb-3">
            <label for="propertyAddress" class="form-label">Address</label>
            <textarea class="form-control" required id="propertyAddress" name="address" required></textarea>
          </div>
          <div class="mb-3">
            <label for="propertLocation" class="form-label">Location</label>
            <input type="text" required class="form-control" id="propertyLocation" name="location" required>
          </div>
          <div class="mb-3">
            <label for="propertyFeatures" class="form-label">Features</label>
            <textarea required class="form-control" id="propertyFeatures" name="features" required></textarea>
          </div>
          <div class="mb-3">
            <label for="propertyImage" class="form-label">Choose Property Image</label>
            <input type="file" required class="form-control" id="propertyImage" name="image" required>
          </div>
          <!-- Add other property details here -->

          <button type="submit" class="btn btn-primary">Add Property</button>
        </form>
      </div>
    </div>
  </div>
</div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
  </body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Real Estate Management System</title>
    <style>
      body {
        background: url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D') center/cover no-repeat fixed;
      }
      .container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        flex-direction: column; 
      }
  
      .title {
        font-family: 'Comic Sans MS', cursive;
        font-size: 24px;
        color: #fff;
        margin-bottom: 20px;
      }
  
      .card {
        background: rgba(255, 255, 255, 0.8);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        width: 100%;
        max-width: 400px;
      }
    </style>
    
  </head>

      <body class="bg-light">

        {% if messages %}
        <div class="d-flex align-items-center justify-content-center mt-4">
          <div class="alert alert-warning alert-dismissible fade show w-50" role="alert">
              {% for message in messages %}
              <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              {% endfor %}
          </div>
        </div>
          {% endif %}

        <div class="container">
          <div class="title">
            <h1>Real Estate Management System</h1>
          </div>
          <div class="card">
            <div class="card-header">
              <h3 class="text-center">Login</h3>
            </div>
            <div class="card-body">
              <form action="/" method='POST'>
                {% csrf_token %}
                <div class="form-group">
                  <label for="inputEmail">Email address</label>
                  <input type="email" name="email" class="form-control" id="inputEmail" style="margin-bottom: 10px;" placeholder="Enter email">
                </div>
                <div class="form-group">
                  <label for="inputPassword">Password</label>
                  <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password" style="margin-bottom: 15px;">
                </div>
                <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block">Login</button>
                </div>
              </form>
            </div>
          </div>
        </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/viewproperty.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Real Estate Management System</title>
    <style>
      body {
        background: url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D') center/cover no-repeat fixed;
      }

      .title {
        font-family: 'Comic Sans MS', cursive;
        font-size: 24px;
        color: #5c8a8a;
        margin-bottom: 20px;
        text-align:center;
      }
  

    </style>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        
        <div class="container-fluid">
          <a class="navbar-brand" href="/home/">Real Estate</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/home/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/home/">Our Properties</a>
              </li>
      
              <li class="nav-item">
                <a class="nav-link" href="/tenant/" tabindex="-1" aria-disabled="true">Our Tenants</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout/" tabindex="-1" aria-disabled="true">Logout</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
          <div class="title">
            <h1>Unit Details</h1>
          </div>

          <div class="d-flex align-items-center justify-content-center mt-4">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPropertyModal">Add Unit</button>
          </div>

              {% if messages %}
          <div class="d-flex align-items-center justify-content-center mt-4">
            <div class="alert alert-warning alert-dismissible fade show w-50" role="alert">
                {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {% endfor %}
            </div>
          </div>
            {% endif %}

          <div class="container mt-5">
            <div class="row justify-content-center">
                
              <div class="col-md-6">
                {% for data in tenant_det %}
                <div class="card mt-3">
                  <div class="card-body">
                    <h3 class="card-title">{{data.unit.name}}</h3>
                    <p class="card-text">{{data.unit.features}}</p>
                    <p class="card-text">Type : <strong>{{data.unit.type}}</strong></p>
                    <p class="card-text">Rent : <strong>{{data.unit.rent_cost}}/-</strong></p>

                  </div>
                  <ul class="list-group list-group-flush">
                    {% if data.unit.is_available == True %}
                    <a href="{% url 'core:allocate_tenant' unit=data.unit.id prop=property.id %}" class="btn btn-primary">Allocate to Tenant</a>
                    {% else %}
                    <li class="list-group-item">Assigned Tenant : {{data.tenant.name}}</li>
                    <li class="list-group-item">Egreement End Date : {{data.tenant.lease_expiry_date|date:"Y/m/d"}}</li>
                    {% endif %}
                 
                  </ul>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>

          <div class="modal fade" id="addPropertyModal" tabindex="-1" aria-labelledby="addPropertyModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="addPropertyModalLabel">Add New Unit In {{property.name}}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
          
                  <form id="addUnitForm" action="{% url 'core:add_unit' id=property.id %}" method = 'POST'>
                    {% csrf_token %}
          
                    <div class="mb-3">
                      <label for="UnitName" class="form-label">Unit Name</label>
                      <input type="text" required class="form-control" id="UnitName" name="name" required>
                    </div>
                    <div class="mb-3">
                      <label for="UnitType" class="form-label">Type</label>
                      <select class="form-select" id="UnitType" name="type" required>
                          <option value="1BHK">1BHK</option>
                          <option value="2BHK">2BHK</option>
                          <option value="3BHK">3BHK</option>
                          <option value="4BHK">4BHK</option>
                      </select>
                    </div>
                    <div class="mb-3">
                      <label for="UnitLocation" class="form-label">Rent</label>
                      <input type="number" step="0.01" required class="form-control" id="UnitLocation" name="rent" required>
                    </div>
                    <div class="mb-3">
                      <label for="UnitFeatures" class="form-label">Features</label>
                      <textarea required class="form-control" id="UnitFeatures" name="features" required></textarea>
                    </div>
     
                    <!-- Add other Unit details here -->
          
                    <button type="submit" class="btn btn-primary">Add Property</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <br>
          <br>
      



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>